/*
Kafka Bridge API Reference

Testing TopicsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kafka_bridge

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tihaya-anon/tx_sys-event-event_repository/src/kafka_bridge"
)

func Test_kafka_bridge_TopicsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TopicsAPIService CreateTopic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.TopicsAPI.CreateTopic(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService GetOffsets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string
		var partitionid int32

		resp, httpRes, err := apiClient.TopicsAPI.GetOffsets(context.Background(), topicname, partitionid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService GetPartition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string
		var partitionid int32

		resp, httpRes, err := apiClient.TopicsAPI.GetPartition(context.Background(), topicname, partitionid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService GetTopic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string

		resp, httpRes, err := apiClient.TopicsAPI.GetTopic(context.Background(), topicname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService ListPartitions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string

		resp, httpRes, err := apiClient.TopicsAPI.ListPartitions(context.Background(), topicname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService ListTopics", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TopicsAPI.ListTopics(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService Send", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string

		resp, httpRes, err := apiClient.TopicsAPI.Send(context.Background(), topicname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TopicsAPIService SendToPartition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string
		var partitionid int32

		resp, httpRes, err := apiClient.TopicsAPI.SendToPartition(context.Background(), topicname, partitionid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
