/*
Kafka Bridge API Reference

Testing ProducerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package kafka_bridge

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tihaya-anon/tx_sys-event-event_repository/src/kafka_bridge"
)

func Test_kafka_bridge_ProducerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProducerAPIService Send", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string

		resp, httpRes, err := apiClient.ProducerAPI.Send(context.Background(), topicname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProducerAPIService SendToPartition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string
		var partitionid int32

		resp, httpRes, err := apiClient.ProducerAPI.SendToPartition(context.Background(), topicname, partitionid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
