apiVersion: v1
kind: Service
metadata:
  name: event-repository
  labels:
    app: event-repository
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: event-repository
