/*
Kafka Bridge API Reference

The Kafka Bridge provides a REST API for integrating HTTP based client applications with a Kafka cluster. You can use the API to create and manage consumers and send and receive records over HTTP rather than the native Kafka protocol. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafka_bridge

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RecordKey - Key representation for a record. It can be an array, a JSON object or a string
type RecordKey struct {
	ArrayOfAny *[]interface{}
	MapmapOfStringAny *map[string]interface{}
	String *string
}

// []interface{}AsRecordKey is a convenience function that returns []interface{} wrapped in RecordKey
func ArrayOfAnyAsRecordKey(v *[]interface{}) RecordKey {
	return RecordKey{
		ArrayOfAny: v,
	}
}

// map[string]interface{}AsRecordKey is a convenience function that returns map[string]interface{} wrapped in RecordKey
func MapmapOfStringAnyAsRecordKey(v *map[string]interface{}) RecordKey {
	return RecordKey{
		MapmapOfStringAny: v,
	}
}

// stringAsRecordKey is a convenience function that returns string wrapped in RecordKey
func StringAsRecordKey(v *string) RecordKey {
	return RecordKey{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RecordKey) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfAny
	err = newStrictDecoder(data).Decode(&dst.ArrayOfAny)
	if err == nil {
		jsonArrayOfAny, _ := json.Marshal(dst.ArrayOfAny)
		if string(jsonArrayOfAny) == "{}" { // empty struct
			dst.ArrayOfAny = nil
		} else {
			if err = validator.Validate(dst.ArrayOfAny); err != nil {
				dst.ArrayOfAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfAny = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfAny = nil
		dst.MapmapOfStringAny = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RecordKey)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RecordKey)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RecordKey) MarshalJSON() ([]byte, error) {
	if src.ArrayOfAny != nil {
		return json.Marshal(&src.ArrayOfAny)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RecordKey) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfAny != nil {
		return obj.ArrayOfAny
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RecordKey) GetActualInstanceValue() (interface{}) {
	if obj.ArrayOfAny != nil {
		return *obj.ArrayOfAny
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRecordKey struct {
	value *RecordKey
	isSet bool
}

func (v NullableRecordKey) Get() *RecordKey {
	return v.value
}

func (v *NullableRecordKey) Set(val *RecordKey) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordKey) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordKey(val *RecordKey) *NullableRecordKey {
	return &NullableRecordKey{value: val, isSet: true}
}

func (v NullableRecordKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


