/*
Kafka Bridge API Reference

The Kafka Bridge provides a REST API for integrating HTTP based client applications with a Kafka cluster. You can use the API to create and manage consumers and send and receive records over HTTP rather than the native Kafka protocol. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafka_bridge

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RecordValue - Value representation for a record. It can be an array, a JSON object or a string
type RecordValue struct {
	ArrayOfAny *[]interface{}
	MapmapOfStringAny *map[string]interface{}
	String *string
}

// []interface{}AsRecordValue is a convenience function that returns []interface{} wrapped in RecordValue
func ArrayOfAnyAsRecordValue(v *[]interface{}) RecordValue {
	return RecordValue{
		ArrayOfAny: v,
	}
}

// map[string]interface{}AsRecordValue is a convenience function that returns map[string]interface{} wrapped in RecordValue
func MapmapOfStringAnyAsRecordValue(v *map[string]interface{}) RecordValue {
	return RecordValue{
		MapmapOfStringAny: v,
	}
}

// stringAsRecordValue is a convenience function that returns string wrapped in RecordValue
func StringAsRecordValue(v *string) RecordValue {
	return RecordValue{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RecordValue) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into ArrayOfAny
	err = newStrictDecoder(data).Decode(&dst.ArrayOfAny)
	if err == nil {
		jsonArrayOfAny, _ := json.Marshal(dst.ArrayOfAny)
		if string(jsonArrayOfAny) == "{}" { // empty struct
			dst.ArrayOfAny = nil
		} else {
			if err = validator.Validate(dst.ArrayOfAny); err != nil {
				dst.ArrayOfAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfAny = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfAny = nil
		dst.MapmapOfStringAny = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RecordValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RecordValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RecordValue) MarshalJSON() ([]byte, error) {
	if src.ArrayOfAny != nil {
		return json.Marshal(&src.ArrayOfAny)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RecordValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfAny != nil {
		return obj.ArrayOfAny
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RecordValue) GetActualInstanceValue() (interface{}) {
	if obj.ArrayOfAny != nil {
		return *obj.ArrayOfAny
	}

	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRecordValue struct {
	value *RecordValue
	isSet bool
}

func (v NullableRecordValue) Get() *RecordValue {
	return v.value
}

func (v *NullableRecordValue) Set(val *RecordValue) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordValue) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordValue(val *RecordValue) *NullableRecordValue {
	return &NullableRecordValue{value: val, isSet: true}
}

func (v NullableRecordValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


